### ISSUE TITLE
Some questions.

### ISSUE THREAD

**Issue by Tas-sos** [nextcloud/admin_notifications#3] opened 2017-02-13 17:34 UTC
First of all thank you for this very interesting application. Congratulations on this your idea.
I hope to help you to do even better.

I first to ask - clarify the following :
What exactly is meant by the following : 

1. `Short message up to 255 characters` and 
2. `Optional: longer message with more details, up to 4000 characters`

the second message may be up to **four thousand** characters ?
because in my tests, not exceeding **one hundred and ten** (110) characters.
Perhaps something similar applies to the short message ( i call it the title of the message ).
For this i wonder if i understand myself something wrong ( about the size of the message ).

I execute the following commands : 
```
cd /var/www/nextcloudFolder

sudo -u www-data php7.0 ./occ notification:generate userX "Message Title" -l "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin orci nisi, maximus ac metus lacinia, convallis elementum metus. Duis eget eleifend urna. Integer tellus justo, aliquam at felis bibendum, vestibulum faucibus magna. Praesent vitae tincidunt lectus. In accumsan pellentesque ornare."
```
I have the following result :
![notif](https://i.imgur.com/b5noyYC.png)
Notice that cuts the message.

Only if execute this command :
```
sudo -u www-data php ./occ notification:generate userX "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin orci nisi, maximus ac metus lacinia, convallis elementum metus. Duis eget eleifend urna. Integer tellus justo, aliquam at felis bibendum, vestibulum faucibus magna. Praesent vitae tincidunt lectus. In accumsan pellentesque ornare."

Too long or empty short-message
```
He returns this error message. But this message is **295** characters.
I understand something wrong or makes a wrong command?

Something else (perhaps you've already noticed), you say to execute this command:
`sudo -u www-data ./occ notification:generate admin "Short message up to 255 characters" -l "Optional: longer message with more details, up to 4000 characters"`

But in my system, i get this error message :
`sudo: ./occ: no command found`

However, adding the "**php**" executed normally :
`sudo -u www-data php ./occ notification:generate admin "Short message up to 255 characters" -l "Optional: longer message with more details, up to 4000 characters"`

Why is this happening ?
Why do i need to write and "php" ?

Something else i want to ask, i can send messages - notifications and in groups?

### Server configuration
**Operating system**:
Ubuntu 16.04.2 LTS ( Server )

**Web server:**
Apache/2.4.18 (Ubuntu)

**Database:**
MariaDB

**PHP version:**
Version 7.

**Nextcloud version:**
Nextcloud 11.0.1 (stable)

**Where did you install Nextcloud from:**
I downloaded the zip file from the [official page](https://nextcloud.com/install/#instructions-server).

**List of activated apps:**

```
sudo -u www-data php occ app:list

Enabled:
  - activity: 2.4.1
  - admin_notifications: 1.0.0
  - comments: 1.1.0
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_markdown: 1.0.0
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - spreed: 1.2.0
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - templateeditor
  - user_external
  - user_ldap
  - user_saml
```

### Client configuration
**Mozilla Firefox 45.7.0**

Thanks you! :)

**Comment by nickvergessen** [comment] 2017-02-14 11:52
Thanks for your feedback, let me reply to them step by step:
I just tested a 3.999 long message and it worked:
```
notification:generate admin "test" -l "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. 

Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. 

Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. 

Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. 

Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis. 

At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, At accusam aliquyam diam diam dolore dolores duo eirmod eos erat, et nonumy sed tempor et et invidunt justo labore Stet clita ea et gubergren, kasd magna no rebum. sanctus sea sed takimata ut vero voluptua. est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat. 

Consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus. Lorem ipsum dolor sit amet, consetetur sadipscing elitr,"
```
I think the problem is that in your second command you miss the `"Message Title" -l` part, which makes it use the long message as the 255 chars subject. And that won't work of course.

> However, adding the "php" executed normally :

That depends on your enviroment. the occ file needs to be executable by the php user etc.

> Something else i want to ask, i can send messages - notifications and in groups?

Currently only users, but sounds like a good feature request.

**Comment by Tas-sos** [comment] 2017-02-14 16:37
It would be really a great pleasure for me, if i helped even in this way ( i hope don't wasting your time unfairly).

So, i execute the following command ( copying from you, just with a little more short message ) :

`sudo -u www-data php ./occ notification:generate UserX "test" -l "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet."
`

but the result was the same again:

![result](https://i.imgur.com/7XJXNAd.png)

Perhaps do you need any further adjustment of server side ?
Personally only just installed the application by the my Nextcloud administrator through the corresponding page.


_P.S. : I forgot to tell you from the beginning, sorry for my bad English._ 

Edit - update : What are the differences between this application here and this here : [Announcement Center for Nextcloud ](https://github.com/nextcloud/announcementcenter), that there not requires applications, beyond the by default basics ? Just randomly I found the above application.

**Comment by nickvergessen** [comment] 2017-02-20 11:26
Yeah the UI simply trims after [100-120 characters](https://github.com/nextcloud/notifications/blob/master/js/notification.js#L84).
Maybe the UI should allow to expand it when it was trimmed in the view.

> What are the differences between this application here and this here : Announcement Center for Nextcloud , that there not requires applications, beyond the by default basics ? Just randomly I found the above application.

This app here is more an API endpoint. While the announcement center is more something like an instance-wide blog.

**Comment by nickvergessen** [comment] 2017-03-08 11:19
I will close this issue now, all questions are either answered or part of other issues/apps.

**Closed as completed by nickvergessen** 2017-03-08 11:19 UTC
